source 'https://rubygems.org'

gem "jekyll", "~> 4.3.4"
gem "just-the-docs"

# Plugins
gem "jekyll-seo-tag"
gem "jekyll-relative-links"

# Required for Ruby 3.4.0+ (removed from standard library)
gem "csv"
gem "base64"
gem "bigdecimal"
